language: node_js
node_js:
- '12'
script:
- yarn lint
cache: yarn
deploy:
  skip_cleanup: true
  provider: npm
  email: domoritz@gmail.com
  api_key:
    secure: fIZkxaoV7vY+FtgmM+fv1ybdZCrHI0L1GKpVGLlLKHaBtKnIfROGkyBtKKgsJn0qrPQmJY9t0ywml0dkUxCiIjHvNdwCXQxypcAtOdZjhvfbMY6r9gW/TjeyH2O2eSWAHbSam/CxYw6fEflE0xypvgUlFZazMzPUZsTP8vZMuDB9t3jdWyXNjcm/faZ5UgKFK6GX8RplkWc1U6NnfrvhmV+UX8AkwbP4sdT9dqu7aDkHaG/O5o8maWGYmsQVhutRK/lr/393kKRlo2jJUgrkNXriw5p4+HwPHafMMv9thhwLMRKZcCap/kEBbw1FxqVe1+CdqLu4fM2sYVVCD/Goxx/9o6L700y4yOzfL+5peRyfZuE+HqgnxhLkd736Dr5xK7eXUfG268XXu9+IPrTbfEPbxiAEBz4cN2LQ85jo+qGgK9CSK84LxwALAW+g256/44sFS6UAxQ+RLm42GKa2++jDgeX5m4sWKJI2T5lB3NOqyJuZPVlXq2ugqOVlJMYUDDey9fNp5WvMlUcytpVQ4lSrrhaYgY9FOCipwqaiVuxHlPlLaBrt6jUUtnNQK5OQjWc+Bg22Afo05Le9jMb4KNf2vjOr2ALdbpOYwbU4FKUdjM1Y7CoBhboC/PCP66BY83k+f6eYfWH+CX/+MT1k3nxaUuqyWgjmQc6mAn4xpv0=
  on:
    tags: true
    repo: vega/vega-lite-dev-config
