language: node_js
node_js:
- '12'
script:
- yarn lint
cache: yarn
deploy:
  skip_cleanup: true
  provider: npm
  email: domoritz@gmail.com
  api_key:
    secure: QNupnSn2MX5SjQQOnaWflP2NBy/Vx15U8IusfK/vAsp3HLHrYwJ2RweulbxGYbhUVIKOKstNeh9BDHeWe2MHBAaQKTlHSLgU4CkKJB2tVamxc/+9Q33N7s7aJHtUxVm/hmGu56jugeZdtZUvlCnRc/RIrpAKcLGZU23Pj43RQC1FQ9M7nOBtPt9mtTNX3FxKZyW5b4Z1fadwzLKsVU3v1XAAh03w93/lsIiI2rU0jLEIGMF4Ajuqg4JJyevhssw8F1a+6wlhGKjlxLYG+VnazJ2dNSFp6pj0Caw3A+w7TkjMscUsRD9Xv0OcW/g/c2Y8mC1XSDAKe2ALwzuU6QvilCPeahLSMPlyXvM8DKfgCoGCnJlWLSYuwWnpwJ2+/pF9ZJ+2MV89WJNCNcVkZ6fWhCLhJtUtWK+yvQw79ElUUDLhIe+A8dazW9Xtfg/f7NaIOb8t877y+6GEhTS9mhRpog2ckwyhLdUQCtAQQEBb5/iBnAvP7PzplG0FpCDF8UBG4t3JFRWWMzXRCugj1UBn/nM1zyfvFR4l+nMTpx7o1NCGq2SNZKk+6leoUYn9bHIYo2WZsgGc6nu8n4/XwZ86+oKfGsKKBgVR7C4z/H4tiBssGcIuI12uUyoMVdtzxEc6BbnQ3RYh9+sT3sbwszXHHcdj6servjosHYDHgm29uOY=
  on:
    tags: true
    repo: vega/vega-lite-dev-config
