language: node_js
node_js:
- '12'
script:
- yarn lint
cache: yarn
deploy:
  skip_cleanup: true
  provider: npm
  email: domoritz@gmail.com
  api_key:
    secure: xtCdhGYiHDNwIHjeK+Yr0CkFB9HRlRa6FDJfGqiFrveTrCGNzNK0l3AOmIlYJyJ7sF9Zzm+dmyBehIh7l4r7Ml4TMM1IM4TpTFXICZOuk19fIIBdNTs2W0UJ1c4AeJkdawVeyYPGC9dfZ0bODXUy7kLzbuv6RXuymN8yj5byjWGCnzFL7VwhQYBTDiWtl2Zyg54ToHk67BrwVnU4AGlahxjirM4zANy5gT4/GuUhKPPTxM8KSeDoSmT8jGVYFcUtDxnausZZVlbq4BiFhLQbtXHutosKu2e8eypp99jaZrEEEm6VtfclF2RbyBlGvsDIuuvrS5oeaensagZo09pa+mft0oe97SFL1Zzj13+p94e164SI0yPKe+L94Ln9jLbjETJzlnwbKdGFDgoco7cV+1u437wtV9nvGUqGSAV5xeOlWSVEOdGkUh/ky44+ZFdpIHuShkHW4MB4czhtCSEg+lin1wNF5Klh6MUHP4GRt3SZEsDzrSoUJ1AfyrfR/WZAL4F9h1RFX7Kr6nQw8rXprMW2u35P6jm+HYCGBw/V7D9z3tZzHxBXGWEDCtIlm8yW8pGznyGBMEpVrl14PAKQTpGateq1k2ksEp6ZSl02FDxIIVj477M39Bhj0Rfrajmm8u/OW6xcF4gU6SS1a4BGW4RhKHAV/st09khEFpsK1Jk=
  on:
    tags: true
    repo: vega/vega-lite-dev-config
